name = Three Column
description = A three column layout.
preview = preview.png
template = threecol-layout

; Regions
regions[header_left]    = Header Left
regions[header_right]   = Header Right
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/threecol/threecol.layout.css