name = Full Width
description = A full width layout no side columns.
preview = preview.png
template = fullwidth-layout

; Regions
regions[header_left]    = Header Left
regions[header_right]   = Header Right
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/fullwidth/fullwidth.layout.css